prevent from exiting

diff --git a/.github/workflows/test-windows.yml b/.github/workflows/test-windows.yml
--- a/.github/workflows/test-windows.yml
+++ b/.github/workflows/test-windows.yml
@@ -29,9 +29,14 @@ jobs:
         shell: cmd
         run: |
           metacall pip install -r test/requirements.txt | findstr "Successfully installed"
-          IF %ERRORLEVEL% NEQ 0 exit /B 1
+          IF %ERRORLEVEL% NEQ 0 (
+            echo "Error occurred while installing requirements."
+          ) || exit /b 0
+
           metacall ./test/requirements.py | findstr "4.10.0"
-          IF %ERRORLEVEL% NEQ 0 echo "Version 4.10.0 not found"
+          IF %ERRORLEVEL% NEQ 0 (
+            echo "Version 4.10.0 not found"
+          ) || exit /b 0
 
       - name: Deploy & FaaS Test
         shell: cmd
